### PR TITLE
Add a basic workflow

### LINKED ISSUE #2: Workflow
If the tables were plain text files (and the tex automatically generated), they'd be easy to use for other things: e.g. a program that generates random results from them.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #2

### CODE REVIEW

**Comment by paulidale** [comment]
Hmmmm, not sure what `dndbook.cls` is but the build fails.  I'm also not sure why it calls the build a success.

By tweaking the permissions and having a cookie, we could have the action create the PDF and commit them.  I'm not sure if this is a good idea.

**Comment by DC23** [comment]
dndbook.cls is from the [DND 5e LaTeX template](https://github.com/rpgtex/DND-5e-LaTeX-Template) that I use to get the formatting.
It will need to be installed into the container for the documents to build.

**Comment by paulidale** [comment]
Thanks, my attempt to clone that git project failed.  I've copied the relevant files instead.

**Comment by DC23** [comment]
I think you need the entire DND 5e package installed, not just a few of the files from that package.
I made a branch from your branch to experiment.

**Comment by DC23** [comment]
I think if you copy the entire checkout of DnD 5e to  lib/dnd, and then change the makefile to define TEXINPUTS=./lib//: before calling pdflatex then it should work.

Actually, I don't see where the action clones the DnD template library. did you add the files manually?

**Comment by DC23** [comment]
It's the installation method they [give here](https://github.com/rpgtex/DND-5e-LaTeX-Template#project-install-using-texinputs).

**Comment by paulidale** [comment]
Yeah, it might.  The clone failed in the previous incarnation :(
It's getting late here and I'm tired....

**Comment by DC23** [comment]
This is hardly a critical project that's worth losing sleep over :)

Unless you really want to do it, I am going to make a Python script that generates the tex from text. The goal is to almost cut and paste right from the website. Of course, webscraping might allow full automation but we are over-engineering already!

**Comment by paulidale** [comment]
Go for the script.  I'd have used Lua rather than Python but I'm fluent in both, so use whatever you are more comfortable with.

**Comment by DC23** [comment]
I haven't used Lua in over 10 years, I'll stick with Python :)

**Comment by DC23** [comment]
Looks like you got it working. Nice :)
Where do the PDFs go after the build? Do they get pushed to the repo?

**Comment by paulidale** [comment]
I've not got the update part working yet...
I'm aiming for the updates to be added as a second commit.

**Comment by paulidale** [comment]
It looks like I've got it working now however.

**Comment by DC23** [comment]
Do you want me to merge and close this PR now and do the PDF updates in a separate PR? That would be helpful to bring your working branch up to date with my changes.

**Comment by paulidale** [comment]
I've removed the update and this can be merged now.
It should rebuild on the merge.

**Pull request merged**
